logging:
  level:
    com:
      example:
        demo: debug
mybatis:
  mapperLocations: 'classpath:/mapper/UsersMapper.xml '
  typeAliasesPackage: 'smm.springboot_ftl.bean  '
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: 123456
    url: jdbc:mysql://localhost:3306/mysql?useUnicode=yes&characterEncoding=utf8
    username: test
  freemarker:
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
    suffix: .ftl
    template-loader-path: classpath:/templates/
